package server

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"glyphtones/utils"

	"github.com/labstack/echo/v5"
)

type searchFilters struct {
	Search        string
	Category      int
	SortBy        string
	Page          int
	Phones        []int
	Effects       []int
	AutoGenerated bool
}

func (s *Server) currentUserID(c *echo.Context) int {
	return s.auth.GetIDFromCookie(c)
}

func (s *Server) isLoggedIn(c *echo.Context) bool {
	return s.currentUserID(c) != 0
}

func isHX(c *echo.Context) bool {
	return c.Request().Header.Get("HX-Request") == "true"
}

func validDisplayID(displayID string) bool {
	return len(displayID) > 5
}

func parseIntOrDefault(value string, fallback int) int {
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func parseCSVInts(value string) []int {
	if value == "" {
		return nil
	}

	seen := make(map[int]struct{})
	result := make([]int, 0)
	for _, raw := range strings.Split(value, ",") {
		id, err := strconv.Atoi(raw)
		if err != nil {
			continue
		}
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		result = append(result, id)
	}
	return result
}

func parseSearchFilters(c *echo.Context) searchFilters {
	return searchFilters{
		Search:        c.QueryParam("s"),
		Category:      parseIntOrDefault(c.QueryParam("c"), 0),
		SortBy:        c.QueryParam("o"),
		Page:          parseIntOrDefault(c.QueryParam("page"), 1),
		Phones:        parseCSVInts(c.QueryParam("p")),
		Effects:       parseCSVInts(c.QueryParam("e")),
		AutoGenerated: c.QueryParam("gen") == "on",
	}
}

func setLastSearchCookie(c *echo.Context, value string, maxAge int) {
	c.SetCookie(&http.Cookie{
		Name:   lastSearchCookieName,
		Value:  value,
		Path:   "/",
		MaxAge: maxAge,
	})
}

func (s *Server) loggedInFromCookie(c *echo.Context) bool {
	_, err := c.Cookie(utils.CookieName)
	return err == nil
}

func randomHex(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("read random bytes: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
