package server

import (
	"net/http/httptest"
	"reflect"
	"testing"

	"github.com/labstack/echo/v5"
)

func TestParseCSVIntsDeduplicatesAndSkipsInvalidValues(t *testing.T) {
	t.Parallel()

	got := parseCSVInts("1,2,2,nope,3")
	want := []int{1, 2, 3}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseCSVInts() = %#v, want %#v", got, want)
	}
}

func TestParseSearchFilters(t *testing.T) {
	t.Parallel()

	e := echo.New()
	req := httptest.NewRequest("GET", "/?s=test&c=2&o=latest&page=3&p=1,2,2&e=4,5&gen=on", nil)
	res := httptest.NewRecorder()
	c := e.NewContext(req, res)

	filters := parseSearchFilters(c)
	if filters.Search != "test" {
		t.Fatalf("Search = %q, want test", filters.Search)
	}
	if filters.Category != 2 {
		t.Fatalf("Category = %d, want 2", filters.Category)
	}
	if filters.SortBy != "latest" {
		t.Fatalf("SortBy = %q, want latest", filters.SortBy)
	}
	if filters.Page != 3 {
		t.Fatalf("Page = %d, want 3", filters.Page)
	}
	if !filters.AutoGenerated {
		t.Fatal("AutoGenerated = false, want true")
	}
	if want := []int{1, 2}; !reflect.DeepEqual(filters.Phones, want) {
		t.Fatalf("Phones = %#v, want %#v", filters.Phones, want)
	}
	if want := []int{4, 5}; !reflect.DeepEqual(filters.Effects, want) {
		t.Fatalf("Effects = %#v, want %#v", filters.Effects, want)
	}
}

func TestParseIntOrDefault(t *testing.T) {
	t.Parallel()

	if got := parseIntOrDefault("bad", 7); got != 7 {
		t.Fatalf("parseIntOrDefault() = %d, want 7", got)
	}
}
