package server

import (
	"database/sql"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"glyphtones/database"
	"glyphtones/templates/components"
	"glyphtones/templates/views"

	"github.com/labstack/echo/v5"
)

func (s *Server) index(c *echo.Context) error {
	if c.QueryParams().Has("reset-filters") {
		setLastSearchCookie(c, "/", -1)
		return c.Redirect(http.StatusTemporaryRedirect, "/")
	}
	if len(c.QueryParams()) == 0 {
		cookie, err := c.Cookie(lastSearchCookieName)
		if err == nil && cookie.Value != "/" {
			return c.Redirect(http.StatusTemporaryRedirect, cookie.Value)
		} else {
			setLastSearchCookie(c, c.Request().RequestURI, 1_000_000)
		}
	} else {
		setLastSearchCookie(c, c.Request().RequestURI, 1_000_000)
	}

	filters := parseSearchFilters(c)
	authorID := s.currentUserID(c)
	ctx := c.Request().Context()

	ringtones, numberOfPages, err := s.store.GetRingtones(ctx, filters.Search, filters.Category, filters.SortBy, filters.Phones, filters.Effects, filters.AutoGenerated, filters.Page, authorID)
	if err != nil {
		if isHX(c) {
			return Render(c, views.OtherError(http.StatusInternalServerError, err))
		}
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	effects, err := s.store.GetEffects(ctx)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	if isHX(c) {
		c.Response().Header().Set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0")
		c.Response().Header().Set("Pragma", "no-cache")
		return Render(c, components.ListOfRingtones(ringtones, effects, numberOfPages, filters.Page, authorID, "", "index"))
	}

	phones, err := s.store.GetPhones(ctx)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}
	for i := range phones {
		phones[i].Selected = containsInt(filters.Phones, phones[i].ID)
	}
	for i := range effects {
		effects[i].Selected = containsInt(filters.Effects, effects[i].ID)
	}

	data := views.IndexData{
		Ringtones:        ringtones,
		Phones:           phones,
		Effects:          effects,
		Category:         filters.Category,
		SortBy:           filters.SortBy,
		SearchQuery:      filters.Search,
		AutoGenerated:    filters.AutoGenerated,
		NumberOfPages:    numberOfPages,
		Page:             filters.Page,
		LoggedInAuthorID: authorID,
	}
	return Render(c, views.Index(data))
}

func (s *Server) author(c *echo.Context) error {
	authorName := c.Param("name")
	if authorName == "" {
		return c.Redirect(http.StatusTemporaryRedirect, "/")
	}

	pageNumber := parseIntOrDefault(c.QueryParam("page"), 1)
	userID := s.currentUserID(c)
	ctx := c.Request().Context()

	ringtones, numberOfPages, err := s.store.GetRingtonesByAuthor(ctx, authorName, pageNumber, userID)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	var effects []database.EffectModel
	if userID == 1 {
		effects, err = s.store.GetEffects(ctx)
		if err != nil {
			return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
		}
	}

	if isHX(c) {
		return Render(c, components.ListOfRingtones(ringtones, effects, numberOfPages, pageNumber, userID, authorName, "profile"))
	}

	author, err := s.store.GetAuthorByName(ctx, authorName)
	if err != nil {
		return Render(c, views.NotFoundView(userID != 0))
	}

	data := views.ProfileData{
		Ringtones:        ringtones,
		Effects:          effects,
		NumberOfPages:    numberOfPages,
		Page:             pageNumber,
		Author:           author,
		LoggedInAuthorId: userID,
	}
	return Render(c, views.Profile(data))
}

func (s *Server) me(c *echo.Context) error {
	userID := s.currentUserID(c)
	if userID == 0 {
		return c.Redirect(http.StatusTemporaryRedirect, "/")
	}

	user, err := s.store.GetAuthor(c.Request().Context(), userID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			s.auth.RemoveAuthCookie(c)
		}
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	return c.Redirect(http.StatusPermanentRedirect, fmt.Sprintf("/author/%s", user.Name))
}

func (s *Server) guide(c *echo.Context) error {
	return Render(c, views.Guide(s.loggedInFromCookie(c)))
}

func (s *Server) dmca(c *echo.Context) error {
	return Render(c, views.Dmca(s.loggedInFromCookie(c)))
}

func (s *Server) notFound(c *echo.Context) error {
	return Render(c, views.NotFoundView(s.loggedInFromCookie(c)))
}

func (s *Server) authorRenameView(c *echo.Context) error {
	authorID := s.currentUserID(c)
	if authorID == 0 {
		return Render(c, views.OtherErrorView(http.StatusBadRequest, errors.New("You're not logged in.")))
	}
	author, err := s.store.GetAuthor(c.Request().Context(), authorID)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	return Render(c, components.EditName(author.Name, nil))
}

func (s *Server) authorRename(c *echo.Context) error {
	authorID := s.currentUserID(c)
	if authorID == 0 {
		return errors.New("You're not logged in.")
	}
	newName := strings.ToLower(strings.TrimSpace(c.FormValue("name")))
	if !authorNameR.MatchString(newName) {
		return Render(c, components.EditName(
			newName,
			errors.New("Invalid name. Maximal length is 20 letters. Only letters, numbers and '_-' are allowed.")),
		)
	}
	if err := s.store.RenameAuthor(c.Request().Context(), authorID, newName); err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, errors.New("Something went wrong")))
	}

	c.Response().Header().Add("HX-Redirect", "/me")

	return c.NoContent(http.StatusOK)
}

func containsInt(values []int, target int) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
