package server

import (
	"database/sql"
	"errors"
	"fmt"
	"maps"
	"net/http"
	"slices"
	"strconv"
	"strings"

	"glyphtones/database"
	"glyphtones/templates/components"
	"glyphtones/templates/views"
	"glyphtones/utils"

	"github.com/labstack/echo/v4"
)

func (s *Server) index(c echo.Context) error {
	if c.QueryParams().Has("reset-filters") {
		c.SetCookie(&http.Cookie{
			Name:   lastSearchCookieName,
			Value:  "/",
			MaxAge: -1,
		})
		c.Redirect(http.StatusTemporaryRedirect, "/")
	}
	if len(c.QueryParams()) == 0 {
		cookie, err := c.Cookie(lastSearchCookieName)
		if err == nil && cookie.Value != "/" {
			c.Redirect(http.StatusTemporaryRedirect, cookie.Value)
		} else {
			c.SetCookie(&http.Cookie{
				Name:   lastSearchCookieName,
				Value:  c.Request().RequestURI,
				MaxAge: 1_000_000,
			})
		}
	} else {
		c.SetCookie(&http.Cookie{
			Name:   lastSearchCookieName,
			Value:  c.Request().RequestURI,
			MaxAge: 1_000_000,
		})
	}

	authorID := s.auth.GetIDFromCookie(c)

	searchQuery := c.QueryParam("s")
	category, err := strconv.Atoi(c.QueryParam("c"))
	if err != nil {
		category = 0
	}
	sortBy := c.QueryParam("o")
	pageNumber, err := strconv.Atoi(c.QueryParam("page"))
	if err != nil {
		pageNumber = 1
	}
	includeAutoGenerated := c.QueryParam("gen") == "on"

	phonesMap := make(map[int]bool)
	effectsMap := make(map[int]bool)
	phonesQuery := strings.Split(c.QueryParam("p"), ",")
	effectsQuery := strings.Split(c.QueryParam("e"), ",")
	for _, v := range phonesQuery {
		phoneID, err := strconv.Atoi(v)
		if err == nil {
			phonesMap[phoneID] = true
		}
	}
	for _, v := range effectsQuery {
		effectID, err := strconv.Atoi(v)
		if err == nil {
			effectsMap[effectID] = true
		}
	}

	phonesArr := slices.Collect(maps.Keys(phonesMap))
	effectsArr := slices.Collect(maps.Keys(effectsMap))

	if c.Request().Header.Get("HX-Request") == "true" {
		var ringtones []database.RingtoneModel
		var numberOfPages int

		ringtones, numberOfPages, err = database.GetRingtones(searchQuery, category, sortBy, phonesArr, effectsArr, includeAutoGenerated, pageNumber, authorID)
		if err != nil {
			return Render(c, views.OtherError(http.StatusInternalServerError, err))
		}
		c.Response().Header().Set("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0")
		c.Response().Header().Set("Pragma", "no-cache")
		return Render(c, components.ListOfRingtones(ringtones, numberOfPages, pageNumber, authorID, "", "index"))
	}

	phones, err := database.GetPhones()
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}
	effects, err := database.GetEffects()
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	var ringtones []database.RingtoneModel
	var numberOfPages int

	ringtones, numberOfPages, err = database.GetRingtones(searchQuery, category, sortBy, phonesArr, effectsArr, includeAutoGenerated, pageNumber, authorID)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	for i := range phones {
		phones[i].Selected = phonesMap[phones[i].ID]
	}
	for i := range effects {
		effects[i].Selected = effectsMap[effects[i].ID]
	}

	data := views.IndexData{
		Ringtones:        ringtones,
		Phones:           phones,
		Effects:          effects,
		Category:         category,
		SortBy:           sortBy,
		SearchQuery:      searchQuery,
		AutoGenerated:    includeAutoGenerated,
		NumberOfPages:    numberOfPages,
		Page:             pageNumber,
		LoggedInAuthorID: authorID,
	}
	return Render(c, views.Index(data))
}

func (s *Server) author(c echo.Context) error {
	authorName := c.Param("name")
	if authorName == "" {
		return c.Redirect(http.StatusTemporaryRedirect, "/")
	}

	pageNumber, err := strconv.Atoi(c.QueryParam("page"))
	if err != nil {
		pageNumber = 1
	}

	userID := s.auth.GetIDFromCookie(c)

	ringtones, numberOfPages, err := database.GetRingtonesByAuthor(authorName, pageNumber, userID)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	if c.Request().Header.Get("HX-Request") == "true" {
		return Render(c, components.ListOfRingtones(ringtones, numberOfPages, pageNumber, userID, authorName, "profile"))
	}

	author, err := database.GetAuthorByName(authorName)
	if err != nil {
		return Render(c, views.NotFoundView(userID != 0))
	}

	_, err = c.Cookie(utils.CookieName)
	data := views.ProfileData{
		Ringtones:        ringtones,
		NumberOfPages:    numberOfPages,
		Page:             pageNumber,
		Author:           author,
		LoggedInAuthorId: userID,
	}
	return Render(c, views.Profile(data))
}

func (s *Server) me(c echo.Context) error {
	userID := s.auth.GetIDFromCookie(c)
	if userID == 0 {
		return c.Redirect(http.StatusTemporaryRedirect, "/")
	}

	user, err := database.GetAuthor(userID)
	if err != nil {
		if err == sql.ErrNoRows {
			s.auth.RemoveAuthCookie(c)
		}
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	return c.Redirect(http.StatusPermanentRedirect, fmt.Sprintf("/author/%s", user.Name))
}

func (s *Server) guide(c echo.Context) error {
	_, err := c.Cookie(utils.CookieName)
	return Render(c, views.Guide(err == nil))
}

func (s *Server) dmca(c echo.Context) error {
	_, err := c.Cookie(utils.CookieName)
	return Render(c, views.Dmca(err == nil))
}

func (s *Server) notFound(c echo.Context) error {
	_, err := c.Cookie(utils.CookieName)
	return Render(c, views.NotFoundView(err == nil))
}

func (s *Server) authorRenameView(c echo.Context) error {
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return Render(c, views.OtherErrorView(http.StatusBadRequest, errors.New("You're not logged in.")))
	}
	author, err := database.GetAuthor(authorID)
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	return Render(c, components.EditName(author.Name, nil))
}

func (s *Server) authorRename(c echo.Context) error {
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return errors.New("You're not logged in.")
	}
	newName := strings.ToLower(strings.Trim(c.FormValue("name"), " "))
	if !authorNameR.MatchString(newName) {
		return Render(c, components.EditName(
			newName,
			errors.New("Invalid name. Maximal length is 20 letters. Only letters, numbers and '_-' are allowed.")),
		)
	}
	err := database.RenameAuthor(authorID, newName)
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, errors.New("Something went wrong")))
	}

	c.Response().Header().Add("HX-Redirect", "/me")

	return c.NoContent(http.StatusOK)
}
