package server

import (
	"database/sql"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"glyphtones/database"
	"glyphtones/templates/components"
	"glyphtones/templates/views"
	"glyphtones/utils"

	"github.com/labstack/echo/v4"
	"github.com/lib/pq"
)

func (s *Server) renameView(c echo.Context) error {
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return Render(c, views.OtherErrorView(http.StatusBadRequest, errors.New("You're not logged in.")))
	}

	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	ringtone, err := database.GetRingtone(displayID, authorID)
	if err != nil {
		return c.NoContent(http.StatusInternalServerError)
	}

	return Render(c, components.Rename(ringtone, nil))
}

func (s *Server) rename(c echo.Context) error {
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return errors.New("You're not logged in.")
	}
	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	newName := c.FormValue("name")
	if !ringtoneNameR.MatchString(newName) {
		ringtone, err := database.GetRingtone(displayID, authorID)
		if err != nil {
			return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
		}
		ringtone.Name = newName
		return Render(c, components.Rename(ringtone, errors.New("The name must be 2-20 letters and only a-z and some special characters.")))
	}
	err := database.RenameRingtone(displayID, newName, authorID)
	if err != nil {
		ringtone, err := database.GetRingtone(displayID, authorID)
		if err != nil {
			return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
		}
		return Render(c, components.Rename(ringtone, errors.New("Something went wrong")))
	}
	ringtone, err := database.GetRingtone(displayID, authorID)
	if err != nil {
		return Render(c, components.Rename(ringtone, errors.New("Something went wrong")))
	}

	return Render(c, components.Captions(ringtone, true))
}

func (s *Server) uploadView(c echo.Context) error {
	effects, err := database.GetEffects()
	if err != nil {
		return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
	}

	_, err = c.Cookie(utils.CookieName)
	return Render(c, views.Upload(err == nil, c.FormValue("c"), effects, "", "", nil))
}

func (s *Server) uploadFile(c echo.Context) error {
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return Render(c, views.OtherError(http.StatusBadRequest, errors.New("Only logged-in authors can upload Glyphtones")))
	}
	author, err := database.GetAuthor(authorID)
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, errors.New("Something went wrong")))
	}

	errorHandler := func(mainErr error) error {
		effects, err := database.GetEffects()
		if err != nil {
			return Render(c, views.OtherErrorView(http.StatusInternalServerError, err))
		}
		return Render(c, views.UploadForm(c.FormValue("c"), effects, c.FormValue("e"), c.FormValue("name"), authorID != 0, mainErr))
	}

	if author.Banned {
		log.Println("ban")
		return errorHandler(errors.New("You cannot upload since you are banned!"))
	}

	name := c.FormValue("name")
	if !ringtoneNameR.MatchString(name) {
		return errorHandler(errors.New("Name must be 2-30 characters long and without diacritics."))
	}
	category, err1 := strconv.Atoi(c.FormValue("c"))
	effect, err2 := strconv.Atoi(c.FormValue("e"))
	if err1 != nil || err2 != nil || c.FormValue("gen") == "" {
		return errorHandler(errors.New("Missing form values."))
	}
	autoGenerated := c.FormValue("gen") == "true"
	file, err := c.FormFile("ringtone")
	if err != nil {
		return errorHandler(errors.New("Missing the file."))
	}
	split := strings.Split(file.Filename, ".")
	if len(split) == 0 || split[len(split)-1] != "ogg" {
		return errorHandler(errors.New("It seems that the file provided is not a Nothing Glyphtone."))
	}

	src, err := file.Open()
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}
	defer src.Close()

	tmpFile, err := utils.CreateTemporaryFile(src)
	if err != nil {
		log.Println(err)
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}
	defer func() {
		name := tmpFile.Name()
		tmpFile.Close()
		utils.DeleteFile(name)
	}()

	stats, err := os.Stat(tmpFile.Name())
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}
	if stats.Size() > maxRingtoneSize {
		return errorHandler(errors.New("The file is too large! (3MB limit)"))
	}

	hashBytes, err := utils.GetCheckSum(tmpFile)
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	phones, err := database.GetPhones()
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	phonesCompatibleIDs, glyphData, ok := utils.CheckFile(tmpFile, phones)
	if !ok {
		return errorHandler(errors.New("It seems that the file provided is not a Nothing Glyphtone."))
	}

	displayIDName, err := database.CreateRingtone(name, category, phonesCompatibleIDs, effect, authorID, autoGenerated, glyphData, hashBytes)
	if err != nil {
		if pgErr, ok := err.(*pq.Error); ok {
			if pgErr.Code == "23505" && pgErr.Constraint == "ringtone_hash_key" {
				return Render(c, views.OtherError(http.StatusBadRequest, errors.New("You're trying to upload a file which has been uploaded before. Please do not do that...")))
			}
		}
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	err = utils.CreateRingtoneFile(tmpFile, displayIDName)
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	return Render(c, views.SuccessfulUpload())
}

func (s *Server) downloadRingtone(c echo.Context) error {
	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	_, err := c.Cookie(fmt.Sprintf("Glyphtone_%s_downloaded", displayID))
	if err == nil {
		return c.NoContent(http.StatusOK)
	}
	err = database.RingtoneIncreaseDownload(displayID)
	if err != nil {
		return c.NoContent(http.StatusInternalServerError)
	}
	cookie := http.Cookie{
		Name:    fmt.Sprintf("Glyphtone_%s_downloaded", displayID),
		Value:   "true",
		Expires: time.Now().Add(time.Hour * 1_000_000),
		Path:    "/",
	}
	c.SetCookie(&cookie)
	return c.NoContent(http.StatusOK)
}

func (s *Server) deleteRingtone(c echo.Context) error {
	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	authorID := s.auth.GetIDFromCookie(c)
	if authorID == 0 {
		return Render(c, views.OtherError(http.StatusBadRequest, errors.New("You're not logged in.")))
	}

	err := database.DeleteRingtone(displayID, authorID)
	if err != nil {
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	utils.DeleteFile(fmt.Sprintf("%s/%s.ogg", utils.RingtonesDir, displayID))

	c.Response().Header().Set("HX-Refresh", "true")
	return c.NoContent(http.StatusOK)
}

func (s *Server) detailRingtone(c echo.Context) error {
	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	userID := s.auth.GetIDFromCookie(c)

	ringtone, err := database.GetRingtone(displayID, userID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return s.notFound(c)
		}
		fmt.Println(err)
		return Render(c, views.OtherError(http.StatusInternalServerError, err))
	}

	return Render(c, views.Detail(ringtone, userID))
}

func (s *Server) vote(c echo.Context) error {
	displayID := c.Param("displayID")
	if len(displayID) <= 5 {
		return c.NoContent(http.StatusBadRequest)
	}
	userID := s.auth.GetIDFromCookie(c)
	if userID == 0 {
		return c.NoContent(http.StatusUnauthorized)
	}

	vote, err := strconv.Atoi(c.QueryParam("vote"))
	if err != nil || (vote != 0 && vote != 1 && vote != 2) {
		return c.NoContent(http.StatusBadRequest)
	}

	err = database.Vote(userID, displayID, vote)
	if err != nil {
		log.Println(err)
		ringtone, err := database.GetRingtone(displayID, userID)
		if err != nil {
			return c.NoContent(http.StatusInternalServerError)
		}
		return Render(c, components.Votes(ringtone.DisplayID, ringtone.Votes, ringtone.LoggedInAuthorsVote))
	}

	ringtone, err := database.GetRingtone(displayID, userID)
	if err != nil {
		return c.NoContent(http.StatusInternalServerError)
	}

	return Render(c, components.Votes(ringtone.DisplayID, ringtone.Votes, ringtone.LoggedInAuthorsVote))
}
