package server

import (
	"context"
	"errors"
	"fmt"
	"mime/multipart"
	"os"
	"path/filepath"
	"strings"

	"glyphtones/database"
	"glyphtones/utils"

	"github.com/lib/pq"
)

var errDuplicateRingtone = errors.New("duplicate ringtone upload")

type uploadRequest struct {
	Name          string
	Category      int
	Effect        int
	AuthorID      int
	AutoGenerated bool
}

func (s *Server) saveUploadedRingtone(ctx context.Context, req uploadRequest, fileHeader *multipart.FileHeader) error {
	src, err := fileHeader.Open()
	if err != nil {
		return fmt.Errorf("open uploaded file: %w", err)
	}
	defer src.Close()

	tmpFile, err := utils.CreateTemporaryFile(s.cfg.TemporaryDir, src)
	if err != nil {
		return err
	}
	defer func() {
		name := tmpFile.Name()
		if closeErr := tmpFile.Close(); closeErr != nil {
			utils.LogDeleteFileError(name, closeErr)
		}
		utils.LogDeleteFileError(name, utils.DeleteFile(name))
	}()

	stats, err := os.Stat(tmpFile.Name())
	if err != nil {
		return fmt.Errorf("stat temp ringtone file: %w", err)
	}
	if stats.Size() > maxRingtoneSize {
		return fmt.Errorf("the file is too large! (3MB limit)")
	}

	hashBytes, err := utils.GetCheckSum(tmpFile)
	if err != nil {
		return fmt.Errorf("checksum ringtone file: %w", err)
	}

	phones, err := s.store.GetPhones(ctx)
	if err != nil {
		return err
	}

	checkResult, err := utils.CheckFile(tmpFile, phoneSpecsFromModels(phones))
	if err != nil {
		if errors.Is(err, utils.ErrInvalidRingtoneFile) {
			return err
		}
		return fmt.Errorf("inspect ringtone file: %w", err)
	}

	displayID, err := s.store.CreateRingtone(ctx, req.Name, req.Category, checkResult.PhoneIDs, req.Effect, req.AuthorID, req.AutoGenerated, checkResult.GlyphData, hashBytes)
	if err != nil {
		var pgErr *pq.Error
		if errors.As(err, &pgErr) && pgErr.Code == "23505" && pgErr.Constraint == "ringtone_hash_key" {
			return errDuplicateRingtone
		}
		return err
	}

	if err := utils.CreateRingtoneFile(tmpFile, s.cfg.RingtonesDir, displayID); err != nil {
		cleanupErr := s.store.DeleteRingtone(ctx, displayID, req.AuthorID)
		if cleanupErr != nil {
			return fmt.Errorf("write ringtone file: %w (cleanup failed: %v)", err, cleanupErr)
		}
		return fmt.Errorf("write ringtone file: %w", err)
	}

	return nil
}

func phoneSpecsFromModels(phones []database.PhoneModel) []utils.PhoneSpec {
	result := make([]utils.PhoneSpec, 0, len(phones))
	for _, phone := range phones {
		result = append(result, utils.PhoneSpec{
			ID:              phone.ID,
			NumberOfColumns: phone.NumberOfColumns,
			AlternateCols:   phone.NumberOfColumns2,
		})
	}
	return result
}

func hasOGGExtension(filename string) bool {
	return strings.EqualFold(filepath.Ext(filename), ".ogg")
}
