package database

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"math"
	"strings"

	"github.com/blockloop/scan/v2"
	"github.com/lib/pq"
	"github.com/teris-io/shortid"
)

const resultsPerPage = 10

func (s *Store) GetRingtones(ctx context.Context, search string, category int, sortBy string, phones []int, effects []int, autoGenerated bool, page int, authorID int) ([]RingtoneModel, int, error) {
	var ringtones []RingtoneModel

	query := `WITH ringtone_phones AS ( SELECT par.ringtone_id, array_agg(p.name) AS phone_names, array_agg(par.phone_id) AS phone_ids FROM phone_and_ringtone par INNER JOIN phone p ON p.id = par.phone_id GROUP BY par.ringtone_id ), all_ringtones AS ( SELECT r.id, r.display_id, r.name, COALESCE(rp.phone_names, '{}') AS phone_names, COALESCE(rp.phone_ids, '{}') AS phone_ids, r.effect_id, r.author_id, r.downloads, r.time_added, r.category, r.auto_generated, r.glyphs FROM ringtone r LEFT JOIN ringtone_phones rp ON r.id = rp.ringtone_id ), ringtones_matched AS ( SELECT * FROM all_ringtones WHERE (phone_ids && $2 OR COALESCE(array_length($2, 1), 0) = 0) AND (effect_id = ANY ($3) OR COALESCE(array_length($3, 1), 0) = 0) AND ($4 = 0 OR category = $4)) SELECT rm.id, rm.display_id, rm.name, ( CASE WHEN $1 = '' THEN (rm.downloads::FLOAT) / GREATEST (MAX(rm.downloads) OVER (), 1) ELSE similarity (concat(rm.name, u.name), $1) END) AS score, u.id AS author_id, u.name AS author_name, rm.downloads, rm.phone_names, rm.category, rm.auto_generated, rm.glyphs, rm.effect_id, e.name AS effect_name, COUNT(*) OVER () AS results, COUNT(*) FILTER (WHERE up IS TRUE) - COUNT(*) FILTER (WHERE up IS FALSE) AS votes, ( CASE WHEN $8 = 0 THEN 0 ELSE ( CASE WHEN ( SELECT up FROM vote WHERE ringtone_id = rm.id AND author_id = $8) IS FALSE THEN 2 WHEN ( SELECT up FROM vote WHERE ringtone_id = rm.id AND author_id = $8) IS TRUE THEN 1 ELSE 0 END) END) AS user_vote FROM ringtones_matched rm INNER JOIN effect e ON rm.effect_id = e.id INNER JOIN author u ON rm.author_id = u.id LEFT JOIN vote v ON rm.id = v.ringtone_id WHERE (similarity (concat(rm.name, u.name), $1) > 0.05 OR LENGTH($1) < 3) AND (auto_generated = FALSE OR $5 = TRUE) GROUP BY rm.id, rm.display_id, rm.name, rm.downloads, rm.phone_names, rm.category, rm.auto_generated, rm.glyphs, rm.effect_id, u.id, u.name, e.name, rm.time_added`
	if search != "" {
		query += ` ORDER BY score DESC, rm.name`
	} else {
		switch sortBy {
		case "popular":
			query += ` ORDER BY votes DESC, score DESC`
		case "most downloads":
			query += ` ORDER BY score DESC, rm.name`
		case "latest":
			query += ` ORDER BY rm.time_added DESC, rm.name`
		case "name (a-z)":
			query += ` ORDER BY rm.name, score DESC`
		default:
			query += ` ORDER BY votes DESC, score DESC`
		}
	}
	query += ` LIMIT $6 OFFSET $7;`

	rows, err := s.db.QueryContext(ctx, query, search, pq.Array(phones), pq.Array(effects), category, autoGenerated, resultsPerPage, (page-1)*resultsPerPage, authorID)
	if err != nil {
		return nil, 0, fmt.Errorf("query ringtones: %w", err)
	}
	defer rows.Close()

	if err := scan.Rows(&ringtones, rows); err != nil {
		return nil, 0, fmt.Errorf("scan ringtones: %w", err)
	}

	return ringtones, calcPages(ringtones), rows.Err()
}

func (s *Store) GetRingtonesByAuthor(ctx context.Context, authorName string, page int, loggedInUser int) ([]RingtoneModel, int, error) {
	var ringtones []RingtoneModel

	rows, err := s.db.QueryContext(ctx, `WITH ringtones_matched AS ( SELECT r.id, r.display_id, r.name, ARRAY ( SELECT p.name FROM phone_and_ringtone par INNER JOIN phone p ON p.id = par.phone_id WHERE par.ringtone_id = r.id ) as phone_names, r.effect_id, r.author_id, r.downloads, r.category, r.glyphs, r.auto_generated, (downloads::FLOAT) / GREATEST(MAX(downloads) OVER (), 1) AS score, COUNT(*) FILTER ( WHERE up IS TRUE ) - COUNT(*) FILTER ( WHERE up IS FALSE ) AS votes FROM ringtone r FULL OUTER JOIN vote v ON v.ringtone_id = r.id WHERE r.author_id = ( SELECT id FROM author WHERE name = $1 ) GROUP BY ( r.id, r.display_id, r.name, r.downloads, phone_names, r.category, r.auto_generated, r.glyphs, r.time_added ) ) SELECT rm.id, rm.display_id, rm.name, rm.score, u.id AS author_id, u.name AS author_name, rm.downloads, rm.phone_names, rm.category, rm.glyphs, rm.auto_generated, rm.effect_id, e.name AS effect_name, rm.votes, ( CASE WHEN $2 = 0 THEN 0 ELSE ( CASE WHEN ( SELECT up FROM vote WHERE ringtone_id = rm.id AND author_id = $2 ) IS FALSE THEN 2 WHEN ( SELECT up FROM vote WHERE ringtone_id = rm.id AND author_id = $2 ) IS TRUE THEN 1 ELSE 0 END ) END ) AS user_vote, COUNT(*) OVER () AS results FROM ringtones_matched rm INNER JOIN effect e ON rm.effect_id = e.id INNER JOIN author u ON rm.author_id = u.id ORDER BY score DESC LIMIT $3 OFFSET $4;`, authorName, loggedInUser, resultsPerPage, (page-1)*resultsPerPage)
	if err != nil {
		return nil, 0, fmt.Errorf("query author ringtones: %w", err)
	}
	defer rows.Close()

	if err := scan.Rows(&ringtones, rows); err != nil {
		return nil, 0, fmt.Errorf("scan author ringtones: %w", err)
	}

	return ringtones, calcPages(ringtones), rows.Err()
}

func (s *Store) CreateRingtone(ctx context.Context, name string, category int, phones []int, effect int, authorID int, autoGenerated bool, glyphData string, hash []byte) (string, error) {
	displayID, err := shortid.Generate()
	if err != nil {
		return "", fmt.Errorf("generate ringtone id: %w", err)
	}

	var ringtoneID int
	if err := s.db.QueryRowContext(ctx, `INSERT INTO ringtone (display_id, name, category, effect_id, author_id, auto_generated, glyphs, hash) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id;`, displayID, name, category, effect, authorID, autoGenerated, glyphData, hash).Scan(&ringtoneID); err != nil {
		return "", fmt.Errorf("insert ringtone: %w", err)
	}

	if _, err := s.db.ExecContext(ctx, `INSERT INTO phone_and_ringtone (ringtone_id, phone_id) SELECT $1, UNNEST($2::int[])`, ringtoneID, pq.Array(phones)); err != nil {
		return "", fmt.Errorf("insert ringtone phones: %w", err)
	}

	return displayID, nil
}

func (s *Store) DeleteRingtone(ctx context.Context, displayID string, authorID int) error {
	if _, err := s.db.ExecContext(ctx, `DELETE FROM ringtone WHERE display_id = $1 AND (author_id = $2 OR $2 = 1);`, displayID, authorID); err != nil {
		return fmt.Errorf("delete ringtone %s: %w", displayID, err)
	}
	return nil
}

func (s *Store) GetRingtone(ctx context.Context, displayID string, authorID int) (RingtoneModel, error) {
	var ringtone RingtoneModel

	err := s.db.QueryRowContext(ctx, `SELECT r.id, r.display_id, r.name, ARRAY ( SELECT p.name FROM phone_and_ringtone par INNER JOIN phone p ON p.id = par.phone_id WHERE par.ringtone_id = r.id ) as phone_names, u.id AS author_id, u.name AS author_name, e.id AS effect_id, e.name AS effect_name, r.category, r.auto_generated, r.downloads, COUNT(*) FILTER ( WHERE v.up IS TRUE ) - COUNT(*) FILTER ( WHERE v.up IS FALSE ) AS votes, ( CASE WHEN $2 = 0 THEN 0 WHEN ( SELECT up FROM vote WHERE author_id = $2 AND ringtone_id = r.id ) IS TRUE THEN 1 WHEN ( SELECT up FROM vote WHERE author_id = $2 AND ringtone_id = r.id ) IS FALSE THEN 2 ELSE 0 END ) AS user_vote, r.glyphs FROM ringtone r INNER JOIN effect e ON r.effect_id = e.id INNER JOIN author u ON r.author_id = u.id FULL OUTER JOIN vote v ON r.id = v.ringtone_id WHERE r.display_id = $1 GROUP BY ( r.id, r.display_id, r.name, u.id, u.name, e.id, e.name, r.category, r.downloads );`, displayID, authorID).Scan(
		&ringtone.ID,
		&ringtone.DisplayID,
		&ringtone.Name,
		&ringtone.PhoneNames,
		&ringtone.AuthorID,
		&ringtone.AuthorName,
		&ringtone.EffectID,
		&ringtone.EffectName,
		&ringtone.Category,
		&ringtone.AutoGenerated,
		&ringtone.Downloads,
		&ringtone.Votes,
		&ringtone.LoggedInAuthorsVote,
		&ringtone.Glyphs,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ringtone, err
		}
		return ringtone, fmt.Errorf("get ringtone %s: %w", displayID, err)
	}

	return ringtone, nil
}

func (s *Store) RenameRingtone(ctx context.Context, displayID string, name string, authorID int) error {
	if _, err := s.db.ExecContext(ctx, `UPDATE ringtone SET name = $1 WHERE display_id = $2 AND (author_id = $3 OR $3 = 1);`, name, displayID, authorID); err != nil {
		return fmt.Errorf("rename ringtone %s: %w", displayID, err)
	}
	return nil
}

func (s *Store) UpdateRingtoneMetadata(ctx context.Context, displayID string, category int, effectID int, autoGenerated bool) error {
	if _, err := s.db.ExecContext(ctx, `UPDATE ringtone SET category = $1, effect_id = $2, auto_generated = $3 WHERE display_id = $4;`, category, effectID, autoGenerated, displayID); err != nil {
		return fmt.Errorf("update ringtone metadata %s: %w", displayID, err)
	}
	return nil
}

func (s *Store) RingtoneIncreaseDownload(ctx context.Context, displayID string) error {
	if _, err := s.db.ExecContext(ctx, `UPDATE ringtone SET downloads = downloads + 1 WHERE display_id = $1;`, displayID); err != nil {
		return fmt.Errorf("increment ringtone download %s: %w", displayID, err)
	}
	return nil
}

func (s *Store) GetPhones(ctx context.Context) ([]PhoneModel, error) {
	var phones []PhoneModel

	rows, err := s.db.QueryContext(ctx, `SELECT * FROM phone ORDER BY name;`)
	if err != nil {
		return nil, fmt.Errorf("query phones: %w", err)
	}
	defer rows.Close()

	if err := scan.Rows(&phones, rows); err != nil {
		return nil, fmt.Errorf("scan phones: %w", err)
	}

	return phones, rows.Err()
}

func (s *Store) GetEffects(ctx context.Context) ([]EffectModel, error) {
	var effects []EffectModel

	rows, err := s.db.QueryContext(ctx, `SELECT * FROM effect ORDER BY id;`)
	if err != nil {
		return nil, fmt.Errorf("query effects: %w", err)
	}
	defer rows.Close()

	if err := scan.Rows(&effects, rows); err != nil {
		return nil, fmt.Errorf("scan effects: %w", err)
	}

	return effects, rows.Err()
}

func (s *Store) GetAuthor(ctx context.Context, id int) (AuthorModel, error) {
	var author AuthorModel

	err := s.db.QueryRowContext(ctx, `SELECT id, name, email, date_joined, banned FROM author WHERE id = $1;`, id).Scan(
		&author.ID,
		&author.Name,
		&author.Email,
		&author.DateJoined,
		&author.Banned,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return author, err
		}
		return author, fmt.Errorf("get author %d: %w", id, err)
	}

	return author, nil
}

func (s *Store) GetAuthorByName(ctx context.Context, name string) (AuthorModel, error) {
	var author AuthorModel

	err := s.db.QueryRowContext(ctx, `SELECT id, name, email, date_joined, banned FROM author WHERE name = $1;`, name).Scan(
		&author.ID,
		&author.Name,
		&author.Email,
		&author.DateJoined,
		&author.Banned,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return author, err
		}
		return author, fmt.Errorf("get author by name %s: %w", name, err)
	}

	return author, nil
}

func (s *Store) CreateAuthor(ctx context.Context, name string, email string) (int, error) {
	email = strings.ToLower(email)

	var authorID int
	if err := s.db.QueryRowContext(ctx, `WITH res AS (INSERT INTO author (name, email) VALUES ($1, $2) ON CONFLICT(email) DO NOTHING RETURNING id) SELECT id FROM res UNION ALL SELECT id FROM author WHERE email = $2 LIMIT 1;`, name, email).Scan(&authorID); err != nil {
		return 0, fmt.Errorf("create author %s: %w", name, err)
	}

	return authorID, nil
}

func (s *Store) RenameAuthor(ctx context.Context, id int, newName string) error {
	if _, err := s.db.ExecContext(ctx, `UPDATE author SET name = $1 WHERE id = $2;`, newName, id); err != nil {
		return fmt.Errorf("rename author %d: %w", id, err)
	}
	return nil
}

func (s *Store) Vote(ctx context.Context, userID int, displayID string, vote int) error {
	var err error
	if vote == 0 {
		_, err = s.db.ExecContext(ctx, `DELETE FROM vote WHERE author_id = $1 AND ringtone_id = (SELECT id FROM ringtone WHERE display_id = $2)`, userID, displayID)
	} else {
		_, err = s.db.ExecContext(ctx, `INSERT INTO vote (author_id, ringtone_id, up) SELECT $1, r.id, $3 FROM ringtone r WHERE r.display_id = $2 AND r.author_id != $1 ON CONFLICT (author_id, ringtone_id) DO UPDATE SET up = EXCLUDED.up;`, userID, displayID, vote == 1)
	}
	if err != nil {
		return fmt.Errorf("vote for ringtone %s: %w", displayID, err)
	}
	return nil
}

func calcPages(ringtones []RingtoneModel) int {
	if len(ringtones) == 0 {
		return 0
	}
	return int(math.Ceil(float64(ringtones[0].NumberOfResults) / float64(resultsPerPage)))
}
